In [1]:
import tensorflow as tf
import numpy as np
import keras 

In [2]:
y_true=7.38905609893065
y_pred=7.38905609893065

In [3]:
# input - target*np.log(input)
y_true - y_pred*np.log(y_true)

-7.38905609893065

In [7]:
B = tf.keras.losses.Poisson()
B.call([7.38905609893065], [7.38905609893065])

2024-08-06 14:10:53.143713: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(), dtype=float32, numpy=-7.389056>

In [8]:
a=tf.nn.log_poisson_loss(log_input=np.array([2], dtype = np.float32),
                         targets = np.array([7.38905609893065], dtype = np.float32),
                         compute_full_loss = False)

a.numpy()

array([-7.389056], dtype=float32)

In [9]:
b=tf.nn.log_poisson_loss(log_input=np.array([2], dtype = np.float32),
                         targets = np.array([7.38905609893065], dtype = np.float32),
                         compute_full_loss = True)

b.numpy()

array([1.9189386], dtype=float32)

In [15]:
# Sterling's approx
# target * log(target) - target * 0.5 * log(2*pi*target)

st = y_pred * np.log(y_pred) - y_pred + 0.5 * np.log(2 * np.pi * y_pred)

print(st)

9.307994632135323


In [16]:
# input - target*np.log(input) + st
y_true - y_pred*np.log(y_true) + st

1.9189385332046722

In [18]:
# So a + st = b
a.numpy() + st 
# it does

array([1.9189386], dtype=float32)

In [19]:
# log_poisson_loss requires log transformed data as input
# Computes log Poisson loss given log_input.
# https://github.com/tensorflow/tensorflow/blob/5bc9d26649cca274750ad3625bd93422617eed4b/tensorflow/python/ops/nn_impl.py#L43-L106


In [24]:
c=tf.nn.log_poisson_loss(log_input=np.array([np.log(2)],dtype=np.float32),
                         targets = np.array([7.38905609893065], dtype=np.float32),
                         compute_full_loss=True)

c.numpy()

array([6.186291], dtype=float32)